### ISSUE TITLE
How to set parameter 'sub_batch_size'?

### ISSUE THREAD

**Issue by KazusaW1999** [VinAIResearch/MagNet#1]
Hi, thanks for your contribution with code. I found that the parameter 'sub_batch_size' is added in 'magnet/options/test.py', but in README.md, the instruction of demo do not given that. How could I set it correctly in this model?

**Comment by KazusaW1999** [comment]
I run it with Tesla V100-SXM2-16GB, and set the 'sub_batch_size' equals to 2, got a CUDA out of memory ERROR. Could you please tell me how to adjust my configuration?

**Comment by hmchuong** [comment]
Hi, thank you for your question. You can read the instruction about test.py here https://github.com/VinAIResearch/MagNet#evaluation
