### ISSUE TITLE
Some problems about Gleason dataset

### ISSUE THREAD

**Issue by liqiokkk** [VinAIResearch/MagNet#11]
Hi, thanks a lot for sharing your interesting and great work. I downloaded the Gleason dataset, but I have some problems.
1.Could you tell me how to vote for the final labels for your work?  Majority vote?
2.The labels seem to contain more than fours classes(013456). Could you tell me how to map it to four classes(benign, Grade 3, Grade 4, and Grade 5)?  Only calculate metrics of class 1,3,4 and 5?
3.Could you provide its training and testing filenames?

**Comment by hmchuong** [comment]
I have replied to your email. Thanks for your interest!

**Comment by mtchiu2** [comment]
> 

Hello,

I'm curious about these questions as well. Would you mind providing answers to them here?

Thanks

**Comment by BubbleSai** [comment]
> Hi, thanks a lot for sharing your interesting and great work. I downloaded the Gleason dataset, but I have some problems. 1.Could you tell me how to vote for the final labels for your work? Majority vote? 2.The labels seem to contain more than fours classes(013456). Could you tell me how to map it to four classes(benign, Grade 3, Grade 4, and Grade 5)? Only calculate metrics of class 1,3,4 and 5? 3.Could you provide its training and testing filenames?

Could you provide a copy of answer to me?
