### ISSUE TITLE
How to train without using pretrained weight weights?

### ISSUE THREAD

**Issue by NiZheGeDuTou** [VinAIResearch/MagNet#12]
Hi, thanks for your contribution with code. How to train without using pretrained weight?
Thank you!!
I love you!

**Comment by hmchuong** [comment]
Do you mean training the backbone https://github.com/VinAIResearch/MagNet#training-backbone-networks? the pretrained weight is from imagenet and we recommend to use that pretrained weight for the best result

**Comment by NiZheGeDuTou** [comment]
**This is my code(Num_class of my dataset is 6.):**
python train.py --dataset BDCI2017 --root data/BDCI2017 --datalist data/list/BDCI2017/train.txt --scales 256-256,512-512,1024-1024,2048-2048 --crop_size 256 256 --input_size 256 256 --num_workers 8 --model fpn --pretrained checkpoints/deepglobe_fpn.pth --num_classes 6 --batch_size 8 --task_name BDCI2017_refinement --lr 0.001

**Such an error occurred at runtime.:**
RuntimeError: Error(s) in loading state_dict for ResnetFPN:
        size mismatch for classify.weight: copying a param with shape torch.Size([7, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([6, 512, 3, 3]).
        size mismatch for classify.bias: copying a param with shape torch.Size([7]) from checkpoint, the shape in current model is torch.Size([6]).

**Comment by hmchuong** [comment]
You are training the refinement module. For a new dataset, you should train the backbone first.

**Comment by hmQ1998** [comment]
> 
兄弟 你的DeepGlobe数据集怎么下载的啊
