### ISSUE TITLE
Training details on methods in Table 4

### ISSUE THREAD

**Issue by mtchiu2** [VinAIResearch/MagNet#14]
Hi,

Thanks for your interesting work.

I'm curious about some details regarding comparison methods in table 4 from your paper. Are all methods compared in the table trained and tested on 256x128 images as you mentioned in sec. 4.2? Could you provide more details on how you trained your model compared to the baseline "downsample" and "patching" methods?

Minor side note, from your backbone training config it seems that you are using HRNetv2-W18s rather than HRNetv2-W18. Am I missing something?

Thanks again.

**Comment by hmchuong** [comment]
All methods are trained and tested with 256x128 images. Patches are 256x128 crops and the whole image is downsampled to 256x128 in downsampling.
For the hrnet18, I used [this config](https://github.com/HRNet/HRNet-Semantic-Segmentation/blob/pytorch-v1.1/experiments/cityscapes/seg_hrnet_w18_small_v2_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml) in the origin implementation.

**Comment by mtchiu2** [comment]
Thanks for the explanations!
