### ISSUE TITLE
How to apply train.py trained parameters to test.py？

### ISSUE THREAD

**Issue by hmQ1998** [VinAIResearch/MagNet#15]
Hello! How to apply the parameters of the refinement module obtained after running the train.py function to test.py, I see that you have given three scales of refinement module parameters in the test of the citydataset.

**Comment by hmchuong** [comment]
It depends on the disparency between scales in each dataset. In cityscapes, we have 3 different refinement modules to have better results. You can use one refinement module or list of refinement weights corresponding to the scales.
