### ISSUE TITLE
Patches and refined locations

### ISSUE THREAD

**Issue by razalberto** [VinAIResearch/MagNet#17]
Hi! 
If we are using 256x128 patches and we refine 32768 locations in them. Doesn't this mean that we are using only the output from the refinement network by overwriting all the pixels predicted by the backbone. Am I missing something? Doesn't locations mean pixels? Thank you in advance.

**Comment by hmchuong** [comment]
it should be 32768 pixels of the whole scale. For example, if the image size is 512 x 256, patch size is 256 x 128, there are 4 patches and we refine 32768 of 512 x 256 pixels.

**Comment by razalberto** [comment]
How can you refine locations from a 512 x 256 pixels image when you are working only with 256x128 pixels images in the network?

**Comment by razalberto** [comment]
@hmchuong Can you please clarify this to me?

**Comment by hmchuong** [comment]
we need to resemble the patches before replacement/refinement. 

Please check from this [line](https://github.com/VinAIResearch/MagNet/blob/main/test.py#L197)

**Comment by razalberto** [comment]
Ok, Thank you. So in the case of using cityscapes dataset we are always refine 32768 pixels from a 2048x1024 image or it depends on the scale? Sorry for wasting your time, that's my last question.

**Comment by razalberto** [comment]
@hmchuong

**Comment by razalberto** [comment]
@hmchuong Can you please give me an answer to my last question?

**Comment by hmchuong** [comment]
It depends on the scale at each step. For 2048x1024, you will have 3 scales for 3 steps: 512 x 256, 1024 x 512, 2048 x 1024. So, for each scale, you refine 32768 pixels.

**Comment by razalberto** [comment]
I got it. Thank you for your time!
