### ISSUE TITLE
Why the input_size of backbone is set to the number of 508×508 on the DeepGlobe dataset experiment?

### ISSUE THREAD

**Issue by DwRolin** [VinAIResearch/MagNet#24]
On the Cityscapes dataset experiment, the input size of the backbone network is set to 256×128, and the original image size is 2048×1024, and the input samples are obtained by integer downsampling. However, on the deepglobe dataset experiment, the input size was set to 508×508 and the original image size was 2448×2448, so the input samples were not obtained by integer downsampling.

In the refinement stage, the coarse segmentation map will be interpolated to the original size. Will the non-integer interpolation result in loss of object edge details and is the 508×508 input size necessary?

**Comment by hmchuong** [comment]
508x508 is the best input size according to GLNet's paper. We keep that for the fair comparison
