### ISSUE TITLE
demo.py: error: --sub_batch_size

### ISSUE THREAD

**Issue by yongjilee** [VinAIResearch/MagNet#26]
usage: demo.py [-h] --dataset DATASET [--root ROOT] [--datalist DATALIST] --scales SCALES --crop_size N   
               [N ...] --input_size N [N ...] [--num_workers NUM_WORKERS] --model MODEL --num_classes     
               NUM_CLASSES --pretrained PRETRAINED
               [--pretrained_refinement PRETRAINED_REFINEMENT [PRETRAINED_REFINEMENT ...]] [--image IMAGE]
               --sub_batch_size SUB_BATCH_SIZE [--n_patches N_PATCHES] --n_points N_POINTS
               [--smooth_kernel SMOOTH_KERNEL] [--save_pred] [--save_dir SAVE_DIR]
demo.py: error: --sub_batch_size

**Comment by yongjilee** [comment]
What is this? How can I deal with this problem? thank you.

**Comment by hmchuong** [comment]
sub_batch_size is the batch size to refine patches. You can set it > 1 if you have larger GPUs. Larger sub_batch_size helps speeding up the inference time.
