### ISSUE TITLE
missing file "hrnet_ocr_w18_train_256x128_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml"

### ISSUE THREAD

**Issue by vince2003** [VinAIResearch/MagNet#6]
Hi @hmchuong ,
I try to train backbone networks with mentioned instruction:

# In ./backbone
python train.py --cfg experiments/cityscapes/hrnet_ocr_w18_train_256x128_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml

Can you upload file "hrnet_ocr_w18_train_256x128_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml" ? or any way as long as I can run above command line (I don't see arg: --cfg in code)
Thank you.

**Comment by hmchuong** [comment]
Hi, make sure you are in the `./backbone` directory. The [file](https://github.com/VinAIResearch/MagNet/blob/main/backbone/experiments/cityscapes/hrnet_ocr_w18_train_256x128_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml) is still there.

**Comment by vince2003** [comment]
I see, Thank you!
